site_name: pypixelcolor
site_url: https://lucagoc.github.io/pypixelcolor/
repo_url: https://github.com/lucagoc/pypixelcolor
repo_name: lucagoc/pypixelcolor

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting_started/installation.md
    - Using CLI: getting_started/cli.md
    - Using WebSocket: getting_started/websocket.md
    - Using Python library: getting_started/library.md
  - Commands:
    - Sending Content: commands/content.md
    - Clock Mode: commands/clock.md
    - Managing Data: commands/data.md
    - Device Settings: commands/settings.md
    - Others: commands/other.md
  - Troubleshooting: 
    - Bluetooth Connection: troubleshooting/bluetooth_connection.md
  - Guides:
    - Custom Fonts: guides/custom_fonts.md
    - Android BLE Logs: guides/android_ble_logs.md

theme:
  name: material
  font:
    text: Red Hat Display
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.action.edit
  logo: assets/pngs/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - assets/css/custom.css

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lucagoc/pypixelcolor

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          name: English
          default: true
        - locale: fr
          name: Français
          nav_translations:
            Home: Accueil
            Getting Started: Bien démarrer
            Commands: Commandes
            Troubleshooting: Dépannage
            Guides: Guides
            Using CLI: Utilisation du CLI
            Using WebSocket: Utilisation de WebSocket
            Using Python library: Utilisation de la bibliothèque Python
            Sending Content: Envoi de contenu
            Clock Mode: Mode horloge
            Managing Data: Gestion des données
            Device Settings: Paramètres de l'appareil
            Others: Autres
            Custom Fonts: Polices personnalisées
            Android BLE Logs: Journaux BLE Android
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: Copyright &copy; 2025 lucagoc | Licensed under the MIT License